language: ruby
bundler_args:
rvm:
  - 2.0.0
script:
  - bundle exec rspec spec
services:
  - redis
addons:
  code_climate:
    repo_token: c91fecbbd9e414e7cc3ad7a7d99207145de0ac65a3368de09e8c19295343d399
